List customTimePMList = [
  {'time': '12:00', 'selected': false, 'slot': 'PM'},
  {'time': '12:30', 'selected': false, 'slot': 'PM'},
  {'time': '13:00', 'selected': false, 'slot': 'PM'},
  {'time': '13:30', 'selected': false, 'slot': 'PM'},
  {'time': '14:00', 'selected': false, 'slot': 'PM'},
  {'time': '14:30', 'selected': false, 'slot': 'PM'},
  {'time': '15:00', 'selected': false, 'slot': 'PM'},
  {'time': '15:30', 'selected': false, 'slot': 'PM'},
  {'time': '16:00', 'selected': false, 'slot': 'PM'},
  {'time': '16:30', 'selected': false, 'slot': 'PM'},
  {'time': '17:00', 'selected': false, 'slot': 'PM'},
  {'time': '17:30', 'selected': false, 'slot': 'PM'},
  {'time': '18:00', 'selected': false, 'slot': 'PM'},
  {'time': '18:30', 'selected': false, 'slot': 'PM'},
  {'time': '19:00', 'selected': false, 'slot': 'PM'},
  {'time': '19:30', 'selected': false, 'slot': 'PM'},
  {'time': '20:00', 'selected': false, 'slot': 'PM'},
  {'time': '20:30', 'selected': false, 'slot': 'PM'},
  {'time': '21:00', 'selected': false, 'slot': 'PM'},
  {'time': '21:30', 'selected': false, 'slot': 'PM'},
  {'time': '22:00', 'selected': false, 'slot': 'PM'},
  {'time': '22:30', 'selected': false, 'slot': 'PM'},
  {'time': '23:00', 'selected': false, 'slot': 'PM'},
  {'time': '23:30', 'selected': false, 'slot': 'PM'},
  {'time': '24:00', 'selected': false, 'slot': 'PM'},
];

List customTimeAMList = [
  {'time': '00:30', 'selected': false, 'slot': 'AM'},
  {'time': '01:00', 'selected': false, 'slot': 'AM'},
  {'time': '01:30', 'selected': false, 'slot': 'AM'},
  {'time': '02:00', 'selected': false, 'slot': 'AM'},
  {'time': '02:30', 'selected': false, 'slot': 'AM'},
  {'time': '03:00', 'selected': false, 'slot': 'AM'},
  {'time': '03:30', 'selected': false, 'slot': 'AM'},
  {'time': '04:00', 'selected': false, 'slot': 'AM'},
  {'time': '04:30', 'selected': false, 'slot': 'AM'},
  {'time': '05:00', 'selected': false, 'slot': 'AM'},
  {'time': '05:30', 'selected': false, 'slot': 'AM'},
  {'time': '06:00', 'selected': false, 'slot': 'AM'},
  {'time': '06:30', 'selected': false, 'slot': 'AM'},
  {'time': '07:00', 'selected': false, 'slot': 'AM'},
  {'time': '07:30', 'selected': false, 'slot': 'AM'},
  {'time': '08:00', 'selected': false, 'slot': 'AM'},
  {'time': '08:30', 'selected': false, 'slot': 'AM'},
  {'time': '09:00', 'selected': false, 'slot': 'AM'},
  {'time': '09:30', 'selected': false, 'slot': 'AM'},
  {'time': '10:00', 'selected': false, 'slot': 'AM'},
  {'time': '10:30', 'selected': false, 'slot': 'AM'},
  {'time': '11:00', 'selected': false, 'slot': 'AM'},
  {'time': '11:30', 'selected': false, 'slot': 'AM'},
];
List customDateList = [
  {'date': '01', 'selected': false},
  {'date': '02', 'selected': false},
  {'date': '03', 'selected': false},
  {'date': '04', 'selected': false},
  {'date': '05', 'selected': false},
  {'date': '06', 'selected': false},
  {'date': '07', 'selected': false},
  {'date': '08', 'selected': false},
  {'date': '09', 'selected': false},
  {'date': '10', 'selected': false},
  {'date': '11', 'selected': false},
  {'date': '12', 'selected': false},
  {'date': '13', 'selected': false},
  {'date': '14', 'selected': false},
  {'date': '15', 'selected': false},
  {'date': '16', 'selected': false},
  {'date': '17', 'selected': false},
  {'date': '18', 'selected': false},
  {'date': '19', 'selected': false},
  {'date': '20', 'selected': false},
  {'date': '21', 'selected': false},
  {'date': '22', 'selected': false},
  {'date': '23', 'selected': false},
  {'date': '24', 'selected': false},
  {'date': '25', 'selected': false},
  {'date': '26', 'selected': false},
  {'date': '27', 'selected': false},
  {'date': '28', 'selected': false},
  {'date': '29', 'selected': false},
  {'date': '30', 'selected': false},
];

List monthList = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
];

List yearsList = [
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2022',
  '2023',
];
